#!/bin/sh
#
# Copyright (C) 2010-2012 Ian Moore <imooreyahoo@gmail.com>
# Copyright (C) 2013-2017 OpenMediaVault Plugin Developers
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SQL_MANAGEMENT_SITE_CONF="/etc/nginx/openmediavault-webgui.d/openmediavault-mysql-management-site.conf"

if [ -e "${SQL_MANAGEMENT_SITE_CONF}" ]; then
    rm ${SQL_MANAGEMENT_SITE_CONF}
fi

if [ "$(omv_config_get "/config/services/mysql/enable_management_site")" != "1" ]; then
    exit 0
fi

cat <<EOF > "${SQL_MANAGEMENT_SITE_CONF}"
location /mysql {
    alias /usr/share/mywebsql;

    index index.php;
    try_files \$uri \$uri/ index.php;

    location ~ \.php$ {
        include fastcgi.conf;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME \$request_filename;
        fastcgi_pass unix:/var/run/php-fpm-openmediavault-mysql.sock;
    }

    location = /mysql/favicon.ico {
        access_log off;
        log_not_found off;
    }

    location = /mysql/robots.txt {
        allow all;
        access_log off;
        log_not_found off;
    }

    location ~ /mysql/\. {
        deny all;
    }

    location ~* /mysql/(?:config)/.*\.php$ {
        deny all;
    }

    location ~* /mysql/\.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires max;
        log_not_found off;
    }
}
EOF

exit 0
