#!/bin/sh
#
# Copyright (C) 2010-2012 Ian Moore <imooreyahoo@gmail.com>
# Copyright (C) 2013-2014 OpenMediaVault Plugin Developers
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

MY_CONFIG="/etc/mysql/my.cnf"
MYSQL_CONFIG="/etc/mysql/conf.d/openmediavault-mysql.cnf"
SQL_MANAGEMENT_SITE_CONF="/etc/nginx/openmediavault-webgui.d/openmediavault-mysql-management-site"

# Enable/disable service
if [ "$(omv_config_get "//services/mysql/enable")" != "1" ]; then
    exit 0
fi

current_data_directory=""

# Get current database location
if [ -e "${MYSQL_CONFIG}" ]; then
    current_data_directory="$(cat ${MYSQL_CONFIG} | grep datadir | sed 's/datadir\s\+=\s\+//g')"
else
    # If not openmediavault mysql config, use standard mysql config file
    if [ -e "${MY_CONFIG}" ]; then
        current_data_directory="$(cat ${MY_CONFIG} | grep datadir | sed 's/datadir\s\+=\s\+//g')"
    else
        echo "Unable to get current database location"
        exit 2
    fi
fi

# Check for MySQL database files
if [ ! -e "${current_data_directory}/ibdata1" ]; then
    echo "Unable to find database files"
    exit 3
fi

# Get data location
data_sharedfolderref=$(omv_config_get "//services/mysql/data.sharedfolderref")
data_directory="$(omv_get_sharedfolder_path "${data_directory}")"

# Create MySQL config file
cat <<EOF > ${MYSQL_CONFIG}
# Configuration for openmediavault-mysql

[mysqld]
EOF

xmlstarlet sel -t -m "//services/mysql" \
    -i "enable_networking != 1" -o "skip-networking" -n -b \
    -i "port != ''" -v "concat('port = ', port)" -n -b \
    -i "bind_address != ''" -v "concat('bind-address = ', bind_address)" -n -b \
    -o "datadir = ${data_directory}" -n -b \
    -i "string-length(extra_options) > 0" -v "extra_options" -n -b \
${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${MYSQL_CONFIG}

chmod 644 ${MYSQL_CONFIG}

if [ "${current_data_directory}" != "${data_directory}" ]; then
    invoke-rc.d mysql stop

    # Take ownership of the shared folder.
    chown mysql:mysql "${data_directory}"

    # Copy current data to the new directory and remove all files from the
    # old.
    cp -rfp ${current_data_directory}/* ${data_directory}/
    rm -rf ${current_data_directory}/*

    invoke-rc.d mysql start
fi
