#!/bin/sh
#
# Copyright (C) 2010-2012 Ian Moore <imooreyahoo@gmail.com>
# Copyright (C) 2013-2014 OpenMediaVault Plugin Developers
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

MY_CONFIG="/etc/mysql/my.cnf"
MYSQL_CONFIG="/etc/mysql/conf.d/openmediavault-mysql.cnf"
SQL_MANAGEMENT_SITE_CONF="/etc/nginx/openmediavault-webgui.d/openmediavault-mysql-management-site"

# Enable/disable service
if [ "$(omv_config_get "//services/mysql/enable")" != "1" ]; then
    exit 0
fi

# Get current database location
if [ -e "${MYSQL_CONFIG}" ]; then
    MYSQL_HOME="$(cat ${MYSQL_CONFIG} | grep datadir | sed 's/datadir\s\+=\s\+//g')"
else
    # If not openmediavault mysql config, use standard mysql config file
    if [ -e "${MY_CONFIG}" ]; then
        MYSQL_HOME="$(cat ${MY_CONFIG} | grep datadir | sed 's/datadir\s\+=\s\+//g')"
    else
        echo "Unable to get current database location"
        exit 2
    fi
fi

# Check for MySQL database files
if [ ! -e "${MYSQL_HOME}/ibdata1" ]; then
    echo "Unable to find database files"
    exit 3
fi

# Get data location
DATA_DIRECTORY_REF=$(omv_config_get "//services/mysql/data.sharedfolderref")
DB_FOLDER="$(omv_get_sharedfolder_path "${DATA_DIRECTORY_REF}")"

# Create MySQL config file
cat <<EOF > ${MYSQL_CONFIG}
# Configuration for openmediavault-mysql

[mysqld]
EOF

xmlstarlet sel -t -m "//services/mysql" \
    -i "enable-networking != 1" -o "skip-networking" -n -b \
    -i "port != ''" -v "concat('port = ', port)" -n -b \
    -i "bindaddress != ''" -v "concat('bind-address = ', bindaddress)" -n -b \
    -o "datadir = ${DB_FOLDER}" -n -b \
    -i "string-length(extraoptions) > 0" -v "extraoptions" -n -b \
${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${MYSQL_CONFIG}

chmod 644 ${MYSQL_CONFIG}

if [ "${MYSQL_HOME}" != "${DB_FOLDER}" ]; then
    invoke-rc.d mysql stop

    if [ ! -d "${DB_FOLDER}" ]; then
        mkdir -p "${DB_FOLDER}"
    fi

    chown mysql:mysql "${DB_FOLDER}"

    cp -rfp ${MYSQL_HOME}/* ${DB_FOLDER}/
    rm -rf ${MYSQL_HOME}

    invoke-rc.d mysql start
fi
