#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

MYSQL_DB_DIR="/var/lib/mysql"

data_drive_to_shared_folder()
{
    name="MySqlData"
    comment="MySQL data location"
    mntentref=$(omv_config_get "//services/mysql/mntentref")
    reldirpath="mysql-data"

    # Prepare JSON data.
    json="{ \"uuid\": \"undefined\", \"name\": \"${name}\", \"comment\": \"${comment}\", \"mntentref\": \"${mntentref}\", \"reldirpath\": \"${reldirpath}\" }"

    # Call omv-rcp and create the shared folder and then filter out the
    # uuid of the new shared folder.
    uuid=$(omv-rpc ShareMgmt set "${json}" | grep -Po '(?<="uuid":")[^"]*')

    # Add the shared folder to the plugin config.
    omv_config_add_element "/config/services/mysql" "data.sharedfolderref" $uuid
}

case "$1" in
    configure)
        if ! omv_config_exists "/config/services/mysql"; then
            echo "Initial configuration."
            object="<enable>0</enable>"
            object="${object}<enable-networking>1</enable-networking>"
            object="${object}<port>3306</port>"
            object="${object}<bindaddress>127.0.0.1</bindaddress>"
            object="${object}<data.sharedfolderref></data.sharedfolderref>"
            object="${object}<extraoptions></extraoptions>"
            object="${object}<enable-management-site>0</enable-management-site>"
            object="${object}<showtab>0</showtab>"
            omv_config_add_element "/config/services" "mysql" "${object}" true
        fi

        if [ ! -d "${MYSQL_DB_DIR}" ]; then
            mkdir -p "${MYSQL_DB_DIR}"
            chown mysql:mysql "${MYSQL_DB_DIR}"
        fi

        if dpkg --compare-versions "$2" lt-nl "1.0.7"; then
			data_drive_to_shared_folder
		fi

        omv_install_fixperms
        omv-mkconf mysql

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
