#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
configure)
    if ! omv_config_exists "/config/services/mysql"; then
        echo "Initial configuration."
        object="<enable>0</enable>"
        object="${object}<enable-networking>1</enable-networking>"
        object="${object}<enable-management-site>0</enable-management-site>"
        object="${object}<extraoptions></extraoptions>"
        object="${object}<port>3306</port>"
		object="${object}<bindaddress>127.0.0.1</bindaddress>"
		object="${object}<password></password>"
		object="${object}<data-root></data-root>"
		object="${object}<mntentref></mntentref>"
        omv_config_add_element "/config/services" "mysql" "${object}" true
    fi

    omv_install_fixperms
    ;;
abort-upgrade|abort-remove|abort-deconfigure)
    ;;
*)
    echo "postinst called with unknown argument" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
