#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_MYSQL_CONF="/etc/mysql/conf.d/openmediavault-mysql.cnf"
OMV_MYSQL_PASSWD="/etc/openmediavault/mysql.cnf"
OMV_MYSQLDUMP_PASSWD="/etc/openmediavault/mysqldump.cnf"
SQL_MANAGEMENT_SITE_CONF="/etc/nginx/openmediavault-webgui.d/openmediavault-mysql-management-site.conf"
SQL_MANAGEMENT_POOL_CONF="/etc/php5/fpm/pool.d/openmediavault-mysql-management-site.conf"

case "$1" in
    purge)
        omv_config_delete "/config/services/mysql"

        if [ -e "${OMV_MYSQL_CONF}" ]; then
            rm -f "${OMV_MYSQL_CONF}"
        fi

        if [ -e "${OMV_MYSQL_PASSWD}" ]; then
            rm -f "${OMV_MYSQL_PASSWD}"
        fi

        if [ -e "${OMV_MYSQLDUMP_PASSWD}" ]; then
            rm -f "${OMV_MYSQLDUMP_PASSWD}"
        fi
    ;;

    remove)
        if [ -e "${SQL_MANAGEMENT_SITE_CONF}" ]; then
            rm ${SQL_MANAGEMENT_SITE_CONF}
        fi

        if [ -e "${SQL_MANAGEMENT_POOL_CONF}" ]; then
            rm ${SQL_MANAGEMENT_POOL_CONF}
        fi

        systemctl reload nginx.service
        systemctl reload php5-fpm.service
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
