#!/bin/sh
#
# Copyright (C) 2010-2012 Ian Moore <imooreyahoo@gmail.com>
# Copyright (C) 2013-2014 OpenMediaVault Plugin Developers
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

PWDFILE="/tmp/.openmediavault-mysql-reset-pwd"

# Nothing to do if service is not enabled
if [ "$(omv_config_get "//services/mysql/enable")" != "1" ]; then
    exit 0
fi

if [ ! -f ${PWDFILE} ]; then
    exit 2
fi

root_pass=`cat ${PWDFILE}`
rm -f ${PWDFILE}

PWFD="/tmp/.openmediavault-mysql"
PWF="/tmp/.openmediavault-mysql/pw.$$"

[ -d ${PWFD} ] || mkdir ${PWFD}
chown mysql:mysql ${PWFD}
chmod 700 ${PWFD}
echo ''>${PWF}
chown mysql:mysql ${PWF}
chmod 400 ${PWF}

cat <<EOF >> ${PWF}
UPDATE mysql.user SET Password=PASSWORD('${root_pass}') WHERE User='root';
FLUSH PRIVILEGES;
EOF

cat <<EOF > /etc/mysql/conf.d/pw.cnf
[mysqld]
init-file = ${PWF}
EOF

invoke-rc.d mysql restart

rm -f /etc/mysql/conf.d/pw.cnf
rm -f ${PWF}
[ -d ${PWFD} ] && find ${PWFD} -type f -user mysql -exec rm {} \;
rmdir ${PWFD}
