#!/bin/sh
#
# Copyright (C) 2010-2012 Ian Moore <imooreyahoo@gmail.com>
# Copyright (C) 2013-2015 OpenMediaVault Plugin Developers
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

# Stop if the service is not enabled.
if [ "$(omv_config_get "/config/services/mysql/enable")" != "1" ]; then
    exit 0
fi


# Do error checks.
if [ -z "${1}" ]; then
    echo "No password file path provided."
    exit 1
fi

mysql_root_password_file="${1}"

if [ ! -f ${mysql_root_password_file} ]; then
    echo "Path to password file provided, but the file was not found."
    exit 1
fi

mysql_root_password=$(cat ${mysql_root_password_file})

if [ -z ${mysql_root_password} ]; then
    echo "Password file provided, but the file is empty."
    exit 1
fi


# Create temporary init file and get the path.
temp_init_file=$(su mysql -s /bin/sh -c mktemp)

cat > ${temp_init_file} <<EOF
UPDATE mysql.user SET Password=PASSWORD('${mysql_root_password}') WHERE User='root';
FLUSH PRIVILEGES;
EOF


# Create the tempory configuration file.
temp_mysql_conf_file="/etc/mysql/conf.d/pw.cnf"

cat > ${temp_mysql_conf_file} <<EOF
[mysqld]
init-file = ${temp_init_file}
EOF


# Restart service to reset the password.
invoke-rc.d mysql restart


# Remove temporary files.
if [ -f "${temp_mysql_conf_file}" ]; then
    rm -f "${temp_mysql_conf_file}"
fi

if [ -f "${temp_init_file}" ]; then
    rm -f "${temp_init_file}"
fi
